/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mymoney;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import com.mymoney.commands.CommandInvoker;
import com.mymoney.config.ApplicationConfig;
import com.mymoney.exceptions.InvalidCommandException;

public class App {
   
    public static void run(String inputFileName) {
        ApplicationConfig applicationConfig = new ApplicationConfig();
        CommandInvoker commandInvoker = applicationConfig.getCommandInvoker();
        BufferedReader reader;
        try {
            reader = new BufferedReader(new FileReader(inputFileName));
            String line = reader.readLine();
            while (line != null) {
                List<String> tokens = Arrays.asList(line.split(" "));
                commandInvoker.executeCommand(tokens.get(0),tokens);
                line = reader.readLine();
            }
            reader.close();
        } catch (IOException | InvalidCommandException e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        /*System.out.println(new App().getGreeting());*/
        run(args[0]);
    }
}
